spring:
  application:
    name: CartandOrder
  config:
    import:
      - optional:classpath:database.yaml
      - optional:classpath:jwt.yaml
server:
  port: 8084
internal:
  service:
    token: ${INTERNAL_SERVICE_TOKEN:}
