import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./css/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = Merriweather({
  variable: "--font-sans",
  weight: "variable",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${fontSans.variable}`}
    >
      <body className="">{children}</body>
    </html>
  );
}
