server:
  port: 8081 # Chạy port 8081 để không đụng với 8080 của con Identity

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gotravel_catalog
    username: gotravel_db
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
